name: crosscompiling

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest Docker image
      run: docker pull pi4j/pi4j-builder:2.0
    - name: Cross-compile in Docker
      run: docker run --user "$(id -u):$(id -g)" --rm --volume $(pwd):/build pi4j/pi4j-builder:2.0
    - name: Make staging directory
      run: mkdir staging
    - name: Copy distribution files to staging
      run: |
        cp -r pi4j-distribution/target/*.deb staging
        cp -r pi4j-distribution/target/*.zip staging
        cp -r pi4j-distribution/target/*.tar.gz staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: pi4j-v2-dist
        path: staging
