name: crosscompiling

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest Docker image
      run: docker pull pi4j/pi4j-builder:2.0
    - name: Cross-compile in Docker
      run: docker run --user "$(id -u):$(id -g)" --rm --volume $(pwd):/build pi4j/pi4j-builder:2.0
    - name: Make staging directory
      run: mkdir staging
    - name: Copy core to staging
      run: |
        cp -r pi4j-core/target/*.jar staging
    - name: Copy libraries to staging
      run: |
        cp -r libraries/pi4j-library-pigpio/target/*.jar staging
    - name: Copy plugins to staging
      run: |
        cp -r plugins/pi4j-plugin-pigpio/target/*.jar staging
        cp -r plugins/pi4j-plugin-raspberrypi/target/*.jar staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: pi4j-v2-dist
        path: staging
